# Site settings
title: Intro to Data Analysis & Visualization
email: laura.d.hughes@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An intro into the fundamentals of data analysis and visualization using Stata and R.
baseurl:  /StataTraining
url:  flaneuse.github.io# the base hostname & protocol for your site
twitter_username: flaneuseks
github_username:  flaneuse

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


