# Site settings
title: Intro to Data Analysis & Visualization
email: tessam@usaid.gov
description: > # this means to ignore newlines until "baseurl:"
  An intro into the fundamentals of data analysis and visualization using Stata
baseurl:  /StataTraining
url:  geocenter.github.io# the base hostname & protocol for your site
twitter_username: flaneuseks
github_username:  flaneuse

# Build settings
markdown: kramdown

# highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  visresources:
    output: true 
  poetry:
    output: true
    permalink: /poetry/:path/


